#!/usr/bin/env ruby

require 'fileutils'
require 'logger'
require 'yaml'
require 'rest-client'
require 'bundler'

class Reviewer
  attr_accessor :pwd, :logger, :backup_path

  def initialize
    @logger = Logger.new(STDOUT)
    @logger.level = Logger::DEBUG
    @pwd = Dir.pwd
    @backup_dir = File.join(@pwd, 'tmp/db_backups')
    @db_config ||= Hash.new { |h,k| h[k] = {} }
  end

  def review
    wrong_call! if ARGV.size != 1
    db_exists? ? backup_db : logger.debug("No DB config found at #{db_file}, skipping backup")
    # if first argument was a number we do the checkout, otherwise we just dump the db with suffix specified as argument
    if pr_number && pr_number.to_i.to_s == pr_number
      checkout_pr
    end
  end

  def restore
    wrong_call! if ARGV.size > 1

    backup_file = restore_db_file_name(ARGV[0])
    if File.exists?(backup_file)
      logger.info "Found backup path at #{backup_file}"
      logger.info "Should I restore this DB version? (y)es (*)no"
      if STDIN.gets.chomp == 'y'
        logger.info "... restoring"
        restore_db(backup_file)
        logger.info "... restored"
      end
    else
      logger.info "No backup file found at #{backup_file}"
    end

    if current_branch != main_branch
      branch_to_delete = current_branch
      checkout_main_branch
      delete_branch(branch_to_delete)
    else
      logger.info "already on main branch #{current_branch}, skipping branch cleanup"
    end
  end

  def cherry_pick
    wrong_call! if ARGV.size != 1
    logger.debug 'pulling latest version from origin remote'
    `git pull`
    if $?.success?
      logger.debug 'pulled from origin'
    else
      logger.fatal 'git pull failed, you can try it manually'
      exit(5)
    end

    add_remote
    remote_info = load_remote_info(pr_number)
    logger.debug "cherry-picking #{remote_info[:name]}/#{remote_info[:branch]}"
    `git cherry-pick #{remote_info[:name]}/#{remote_info[:branch]}`
    if $?.success?
      logger.info "Everything set, happy pushing"
    else
      logger.fatal "Cherry-picking failed, try it yourself by running `git cherry-pick #{remote_info[:name]}/#{remote_info[:branch]}`"
      exit(4)
    end
  end

  def update_source_code
    paths = Bundler.definition.dependencies.map(&:source).compact.map(&:path)
    paths.each do |path|
      logger.debug "updating #{path}"
      Dir.chdir(path) do
        output = `git pull upstream #{current_branch}`
        if $?.success?
          logger.debug "#{path} updated"
        else
          logger.debug output
          logger.error "git pull upsrteam #{current_branch} in #{path} failed, skipping"
        end
      end
    end
  end

  private

  def delete_branch(branch_to_delete)
    result = `git branch -D '#{branch_to_delete}'`
    if $?.success?
      logger.info "branch #{branch_to_delete} deleted"
    else
      logger.warn "branch #{branch_to_delete} was not deleted"
      logger.debug result
    end
  end

  def restore_command(sql_file)
    @restore_command ||= "zcat #{sql_file} | sudo su - postgres -c 'psql -d #{db_name} -f -'"
  end

  def restore_db(filename)
    `#{restore_command(filename)}`
    if $?.success?
      logger.info "DB #{filename} restored"
    else
      logger.fatal "DB restoring failed"
      exit(6)
    end
  end

  def restore_db_file_name(specific = nil)
    File.join(@backup_dir, "pre_review_#{specific || current_branch.sub(/^review\/pr/, '')}.sql.gz")
  end

  def current_branch
    `git rev-parse --abbrev-ref HEAD`.chomp
  end

  def add_remote
    remote_info = load_remote_info(pr_number)
    `git remote  | grep ^#{remote_info[:name]}$`
    if $?.success?
      if (url = `git remote get-url #{remote_info[:name]}`) =~ /\Ahttp/
        change_remote_to_ssh(remote_info[:name], url)
      else
        logger.debug "remote #{remote_info[:name]} is already defined"
      end
    else
      logger.debug "defining remote #{remote_info[:name]} with url #{remote_info[:url]}"
      `git remote add '#{remote_info[:name]}' '#{sshize_url(remote_info[:url])}'`
    end
    logger.debug "fetching from #{remote_info[:name]}"
    `git fetch #{remote_info[:name]}`
    remote_info
  end

  def change_remote_to_ssh(name, url)
    logger.debug "remote #{name} defined using HTTP, redefining to use SSH"
    url = sshize_url(url)
    `git remote set-url #{name} #{url}`
    if $?.success?
      logger.debug "remote url should be fixed to #{url}"
    else
      logger.info "remote url was not updated, trying to conitnue with the old one"
    end
  end

  def sshize_url(url)
    url.chomp.sub('https://github.com/', 'git@github.com:') + '.git'
  end

  def current_project
    project = Dir.pwd.split('/').last.sub(/_upstream$/, '')
    case project
    when 'foreman_tasks'
      'foreman-tasks'
    else
      project
    end
  end

  def load_remote_info(pr)
    token_path = File.expand_path(File.dirname(__FILE__)) + '/.token'
    if File.exists?(token_path)
      token = "access_token=#{File.read(token_path)}"
    else
      token = ''
    end

    data = YAML.load(RestClient.get("https://api.github.com/repos/#{main_github_organization}/#{current_project}/pulls/#{pr}.yaml?#{token}"))
    name = data['head']['repo']['owner']['login'].downcase
    url = data['head']['repo']['html_url']
    branch = data['head']['ref']

    { :name => name, :url => url, :branch => branch }
  end

  def main_github_organization
    case current_project
    when 'katello'
      'katello'
    else
      'theforeman'
    end
  end

  def main_branch
    case current_project
    when 'foreman', 'smart-proxy'
      'develop'
    else
      'master'
    end
  end

  def checkout_main_branch
    `git checkout #{main_branch}`
  end
  
  def checkout_pr
    remote_info = add_remote
    remote_name = remote_info[:name]
    remote_branch = remote_info[:branch]

    `git checkout -b 'review/pr#{pr_number}'`
    unless $?.success?
      logger.fatal 'git checkout failed, failing without pulling'
      exit(2)
    end

    `git pull #{remote_name} #{remote_branch}`
    if $?.success?
      logger.info "Everything set, happy reviewing"
    else
      logger.fatal "Pulling failed, try it yourself by running `git pull #{remote_name} #{remote_branch}`"
      exit(3)
    end
  end

  def wrong_call!
    puts "Usage: #{$0} $PR_NUMBER"
    exit(2)
  end

  def backup_db
    logger.debug "Database file found at #{db_file}, triggering backup"
    return true if verify_target
    result = `#{backup_command}`
    if $?.success?
      logger.debug "backup successfully saved at #{backup_path}"
    else
      logger.fatal 'backup command failed'
      logger.fatal "`#{backup_command}`"
      logger.fatal result
    end
    result
  end

  def verify_target
    FileUtils.mkdir_p @backup_dir
    if File.exists?(backup_path)
      logger.warn "backup already exists at #{backup_path}, should I override it (y)es (s)kip (*)exit?"
      case STDIN.gets.chomp
      when  'y'
        logger.info "... will override #{backup_path} with new snapshot"
        return false
      when 's'
        logger.info "... will skip backup, leaving #{backup_path} as it is"
        return true
      else
        logger.fatal "exiting"
        exit(1)
      end
    end
  end

  def backup_command
    @backup_command ||= "sudo su - postgres -c 'pg_dump --clean #{db_name}' | gzip > #{backup_path}"
  end

  def backup_path
    @backup_path ||= File.join(@backup_dir, backup_name)
  end

  def pr_number
    ARGV[0]
  end

  def backup_name
    "pre_review_#{pr_number}.sql.gz"
  end

  def db_name
    db_config('development')['database']
  end

  def db_user
    db_config('development')['username']
  end

  def db_config(environment)
    @db_config[environment] = YAML.load_file(db_file)[environment]
  end

  def db_exists?
    File.exists?(db_file)
  end

  def db_file
    @db_file ||= File.join(@pwd, 'config/database.yml')
  end
end

case File.basename($0)
  when 'rpr'
    Reviewer.new.review
  when 'crp'
    Reviewer.new.cherry_pick
  when 'rrpr'
    Reviewer.new.restore
  when 'usc'
    Reviewer.new.update_source_code
  else
    raise ArgumentError 'unknown invocation name'
end
